EasyWalletWeb/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using EasyWallet.Business.Abstractions;
using EasyWallet.Business.Models;
using EasyWalletWeb.Infrastructure;
using EasyWalletWeb.ViewModels;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;

namespace EasyWalletWeb.Controllers
{
    public class AuthController : Controller
    {
        private readonly DatabaseContext _context;
        private readonly IUserService _userService;
        private readonly IStringLocalizer<AuthController> _localizer;

        public AuthController(DatabaseContext context, IUserService userService, IStringLocalizer<AuthController> localizer)
        {
            _context = context;
            _userService = userService;
            _localizer = localizer;
        }

        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToRoute("wallet");
            }

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(AuthLogin form)
        {
            var user = await _userService.GetUserByEmailAsync(form.Email);
            if (user == null)
            {
                _userService.FakeHash();
                ModelState.AddModelError("Email", _localizer["InvalidEmailPassword"]);
                return View(form);
            }

            if (!_userService.VerifyPassword(form.Password, user))
            {
                ModelState.AddModelError("Email", _localizer["InvalidEmailPassword"]);
                return View(form);
            }

            await Authenticate(user);

            return RedirectToRoute("wallet");
        }

        public ActionResult Signup()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToRoute("wallet");
            }

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Signup(AuthSignup form)
        {
            if (await _userService.EmailExistsAsync(form.Email))
            {
                ModelState.AddModelError("Email", _localizer["EmailAlreadyRegistered"]);
                return View(form);
            }

            var user = await _userService.CreateUser(form.Email, form.Password, form.Name);

            await Authenticate(user);

            SetInstructionsCookies();

            return RedirectToRoute("wallet");
        }

        private async Task Authenticate(User user)
        {
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                new Claim(ClaimTypes.Name, user.Name),
                new Claim(ClaimTypes.Email, user.Email)
            };

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            var authProperties = new AuthenticationProperties
            {
                AllowRefresh = true,
                IsPersistent = true
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authProperties);
        }

        private void SetInstructionsCookies()
        {
            var instructions = new string[] {
                Constants.InstructionNameWelcome,
                Constants.InstructionNameNewCategory,
                Constants.InstructionNameCategories,
                Constants.InstructionNameBalance,
                Constants.InstructionNameMonthly,
                Constants.InstructionNameHistory
            };

            for (int i = 0; i < instructions.Length; i++)
            {
                Response.Cookies.Append(
                    Constants.InstructionsNamePrefix + instructions[i],
                    string.Empty,
                    new Microsoft.AspNetCore.Http.CookieOptions { IsEssential = true }
                );
            }
        }

        [HttpPost]
        public async Task<ActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToRoute("login");
        }
    }
}

EasyWalletWeb/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using EasyWalletWeb.Infrastructure;
using EasyWalletWeb.Models;
using EasyWalletWeb.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EasyWalletWeb.Controllers
{
    public class ReportsController : Controller
    {
        private readonly DatabaseContext _context;

        public ReportsController(DatabaseContext context)
        {
            _context = context;
        }

        public IActionResult History()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToRoute("login");
            }

            var entriesByMonth = GetEntries().GroupBy(e => new DateTime(e.Date.Year, e.Date.Month, 1));

            var entriesObject = new List<KeyValuePair<DateTime, List<Entry>>>();
            var entryPair = new KeyValuePair<DateTime, List<Entry>>();
            for (int i = 0; i < entriesByMonth.Count(); i++)
            {
                entryPair = new KeyValuePair<DateTime, List<Entry>>(
                    entriesByMonth.ElementAt(i).Key,
                    entriesByMonth.ElementAt(i).ToList()
                );
                entriesObject.Add(entryPair);
            }

            return View(new ReportsHistory { Entries = entriesObject });
        }

        [HttpPost]
        public IActionResult HistoryDelete(int id)
        {
            var entry = _context.Entries.FirstOrDefault(e => e.Id == id);
            if (entry == null || entry.DeletedAt != null)
            {
                return NotFound();
            }

            entry.DeletedAt = DateTime.UtcNow;
            _context.Entries.Update(entry);
            _context.SaveChanges();

            return RedirectToAction("History");
        }

        public IActionResult Monthly()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToRoute("login");
            }

            var entriesByMonth = GetEntries().GroupBy(e => new DateTime(e.Date.Year, e.Date.Month, 1));
            var months = new List<MonthlyItem>();
            var month = new MonthlyItem();

            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            User user = _context.Users.Where(u => u.Id == userId).Include(u => u.Categories).First();
            List<Category> categories = user.Categories;

            for(int i = 0; i < entriesByMonth.Count(); i++)
            {
                month = new MonthlyItem();
                month.Month = entriesByMonth.ElementAt(i).Key;

                foreach(var category in categories)
                {
                    decimal sum = GetSumByCategory(entriesByMonth.ElementAt(i).ToList(), category);
                    if (sum > 0)
                    {
                        month.SpendsByCategory.Add(new KeyValuePair<string, decimal>(category.Name, sum));
                    }
                }

                if (month.SpendsByCategory.Count > 0)
                {
                    months.Add(month);
                }
            }

            return View(new ReportsMonthly { Spends = months });
        }

        public IActionResult Balance()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToRoute("login");
            }

            List<Entry> entries = GetEntries();
            List<Entry> expenses = entries.Where(e => e.Tag.Category.CategoryTypeId == Constants.ExpensesCategoryTypeID).ToList();
            List<Entry> incomes = entries.Where(e => e.Tag.Category.CategoryTypeId == Constants.IncomesCategoryTypeID).ToList();

            var data = new ReportsBalance();

            for (int i = 0; i < expenses.Count; i++)
            {
                data.CurrentBalance -= expenses[i].Amount;
            }

            for (int i = 0; i < incomes.Count; i++)
            {
                data.CurrentBalance += incomes[i].Amount;
            }

            var entriesByMonth = entries.GroupBy(e => new DateTime(e.Date.Year, e.Date.Month, 1, 0, 0, 0));
            decimal balance = data.CurrentBalance;
            Entry entry;

            // Adds last month
            if (entriesByMonth.Count() > 0 && entriesByMonth.ElementAt(0).Key.Month != DateTime.Now.Month)
            {
                data.Months.Add(new KeyValuePair<DateTime, decimal>(
                    entriesByMonth.ElementAt(0).Key,
                    data.CurrentBalance
                ));
            }

            for (int i = 0; i < entriesByMonth.Count(); i++)
            {
                for (int j = 0; j < entriesByMonth.ElementAt(i).Count(); j++)
                {
                    entry = entriesByMonth.ElementAt(i).ElementAt(j);
                    balance += entry.Tag.Category.CategoryTypeId == Constants.ExpensesCategoryTypeID ? entry.Amount : -entry.Amount;
                }

                data.Months.Add(new KeyValuePair<DateTime, decimal>(
                    entriesByMonth.ElementAt(i).Key.AddMonths(-1),
                    balance
                ));
            }

            // Removes first month if it has a zero balance
            if (data.Months.Count > 0 && data.Months[data.Months.Count - 1].Value == 0)
            {
                data.Months.RemoveAt(data.Months.Count - 1);
            }

            return View(data);
        }

        private List<Entry> GetEntries()
        {
            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            User user = _context.Users.Where(u => u.Id == userId).Include(u => u.Categories).First();
            Tag[] tags = _context.Tags.ToArray();
            tags = _context.Tags.Where(t =>
                user.Categories.FirstOrDefault(c => c.Id == t.CategoryId) != null)
                .Include(t => t.Entries)
                .ToArray();

            var entries = new List<Entry>();
            foreach (var t in tags)
            {
                entries.AddRange(t.Entries);
            }

            return entries
                .Where(e => e.DeletedAt == null)
                .OrderByDescending(e => e.Date)
                .ToList();
        }

        private decimal GetSumByCategory(List<Entry> entries, Category category)
        {
            decimal total = 0;

            for (int i = 0; i < entries.Count; i++)
            {
                if (entries[i].Tag.CategoryId == category.Id)
                {
                    total += entries[i].Amount;
                }
            }

            return total;
        }
    }
}

EasyWalletWeb/Controllers/WalletController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using EasyWalletWeb.Infrastructure;
using EasyWalletWeb.Models;
using EasyWalletWeb.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;

namespace EasyWalletWeb.Controllers
{
    //[Authorize]
    public class WalletController : Controller
    {
        private readonly DatabaseContext _context;
        private readonly IStringLocalizer<WalletController> _localizer;        
        
        public WalletController(DatabaseContext context, IStringLocalizer<WalletController> localizer)
        {
            _context = context;
            _localizer = localizer;
        }

        public IActionResult Index()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToRoute("login");
            }

            return View();
        }

        public IActionResult Flor()
        {
            var instructions = new string[] {
                Constants.InstructionNameWelcome,
                Constants.InstructionNameNewCategory,
                Constants.InstructionNameCategories,
                Constants.InstructionNameBalance,
                Constants.InstructionNameMonthly,
                Constants.InstructionNameHistory
            };

            for (int i = 0; i < instructions.Length; i++)
            {
                Response.Cookies.Append(
                    Constants.InstructionsNamePrefix + instructions[i],
                    string.Empty,
                    new Microsoft.AspNetCore.Http.CookieOptions { IsEssential = true }
                );
            }

            return RedirectToRoute("wallet");
        }

        [HttpPost]
        public IActionResult Entry(WalletEntry form)
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToRoute("login");
            }

            EntryValidatorResult result = EntryValidator.Validate(form.Entry, _localizer);

            if (!result.IsValid)
            {
                ModelState.AddModelError("Entry", result.ErrorMessage);
                return View("Index", form);
            }

            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            Category[] categories = _context.Categories
                .Where(c => c.UserId == userId && c.DeletedAt == null)
                .Include(c => c.Tags)
                .ToArray();

            int tagId = default(int);

            foreach (Category c in categories)
            {
                foreach (var t in c.Tags)
                {
                    if (result.Keyword.ToLower() == t.Name.ToLower())
                    {
                        tagId = t.Id;
                        break;
                    }
                }
            }

            if (tagId == default(int))
            {
                var othersCategory = categories.First(c => c.Name == "Others" || c.Name == "Otros");
                var tag = new Tag();
                tag.Name = result.Keyword;
                tag.CategoryId = othersCategory.Id;
                tag.CreatedAt = DateTime.UtcNow;
                tag.IsAutoGenerated = true;
                _context.Tags.Add(tag);
                _context.SaveChanges();

                tagId = _context.Tags.First(t => t.CategoryId == othersCategory.Id && t.Name == result.Keyword).Id;
            }

            DateTime today = DateTime.Now;

            var date = new DateTime(
                form.Date.Year, 
                form.Date.Month, 
                form.Date.Day, 
                today.Hour, 
                today.Minute, 
                today.Second);

            var entry = new Entry
            {
                Amount = result.Amount,
                TagId = tagId,
                Date = date,
                CreatedAt = DateTime.UtcNow
            };

            _context.Entries.Add(entry);
            _context.SaveChanges();
            return View("Index", new WalletEntry { PreviousEntrySaved = true });
        }
    }
}

EasyWalletWeb/Views/Shared/Footer.cshtml
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@{
    var culture = Context.Features.Get<IRequestCultureFeature>();

    var isEnglishSelected = culture.RequestCulture.Culture.TwoLetterISOLanguageName == "en";
}

<footer class="border-top footer text-muted py-2">
    <div class="sw-footer container">
        <div class="footer-info">
            &copy; @DateTime.UtcNow.Year - Simple Wallet
            <span style="font-size: 0.9rem">@Localizer["By"] <a href="http://www.luischicas.com">Luis Chicas</a></span>
        </div>

        <div class="language-selection">
            <i class="fas fa-globe"></i>
            <span class=@(isEnglishSelected ? "font-weight-bold" : "")>
                <a id="lang-en" asp-route="language">EN</a>
            </span>
            <span> | </span>
            <span class=@(isEnglishSelected ? "" : "font-weight-bold")>
                <a id="lang-es" asp-route="language">ES</a>
            </span>
        </div>
    </div>
</footer>

EasyWalletWeb/Views/Shared/NavBar.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

<div id="navbar" class="sw-navbar shadow-sm d-flex align-items-center">
    <a asp-controller="Wallet" asp-action="Index">
        <img src="~/images/logo.png" class="mr-3" width="35" height="30" />
    </a>
    <a asp-controller="Wallet" asp-action="Index">
        <h4 class="my-0 mr-4" style="color:white">Simple Wallet</h4>
    </a>
    <a asp-controller="Wallet" asp-action="Index" class="p-2 mr-2 text-light not-mobile-only">@Localizer["Home"]</a>
    <a asp-controller="Categories" asp-action="Index" class="p-2 mr-2 text-light not-mobile-only">@Localizer["Categories"]</a>
    <a asp-controller="Reports" asp-action="History" class="p-2 mr-auto text-light not-mobile-only">@Localizer["Reports"]</a>
    <a id="logout" asp-controller="Auth" asp-action="Logout" class="p-2 text-light not-mobile-only">@Localizer["Logout"]</a>
    <i id="menu-btn" class="fas fa-bars ml-auto mobile-only" onclick="openNav()"></i>
    <i id="menu-close-btn" class="fas fa-chevron-up mobile-only" onclick="closeNav()"></i>
</div>

<div id="navbar-mobile-extra" class="sw-navbar-mobile-extra mobile-only">
    <div>
        <a id="logout-mobile" asp-controller="Auth" asp-action="Logout" class="mx-auto">@Localizer["Logout"]</a>
    </div>
</div>

<div class="sw-navbar-mobile mobile-only">
    <a asp-controller="Categories" asp-action="Index" class="sw-navbar-mobile-btn">
        @Localizer["Categories"]
    </a>
    <a asp-controller="Reports" asp-action="History" class="sw-navbar-mobile-btn">
        @Localizer["Reports"]
    </a>
</div>

EasyWalletWeb/Views/Shared/_Layout-default.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EasyWalletWeb</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EasyWalletWeb</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - EasyWalletWeb</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

EasyWalletWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/images/icon-144.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/images/icon-114.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/images/icon-72.png">
    <link rel="apple-touch-icon-precomposed" href="~/images/icon-57.png">
    <link rel="shortcut icon" href="~/images/icon-32.png">

    <title>@ViewData["Title"] - Simple Wallet</title>

    <meta name="author" content="Luis Chicas">
    <meta name="description" content="Improve your personal finances. Try the quickest and easiest way to track where your money goes.">

    <meta property="og:title" content="Simple Wallet">
    <meta property="og:url" content="http://simplewalletapp.com" />
    <meta property="og:image" content="http://simplewalletapp.com/images/og-image.jpg">
    <meta property="og:description" content="Improve your personal finances. Try the quickest and easiest way to track where your money goes.">

    <meta name="twitter:card" content="summary" />
    <meta name="twitter:creator" content="@("@luischicasg")" />

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" 
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" 
              crossorigin="anonymous">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
              asp-fallback-href="~/lib/fontawesome/css/all.css"
              integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
              crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/site.min.css" />
    </environment>

    @RenderSection("Styles", required: false)
</head>
<body>

    @RenderBody()

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/language.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/language.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>